# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeritaSport' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BeritaSport
pod 'Alamofire'
pod 'SwiftyJSON'

  target 'BeritaSportTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BeritaSportUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
